In [1]:
import torch

In [2]:
import interp_same as IS

In [3]:
test = torch.arange(5*7,dtype=torch.float32).reshape(1,1,5,7).to("cuda")

In [4]:
test

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10., 11., 12., 13.],
          [14., 15., 16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25., 26., 27.],
          [28., 29., 30., 31., 32., 33., 34.]]]], device='cuda:0')

In [5]:
out = torch.zeros_like(test)

In [6]:
IS.interp_shift_plus(test,out,0.8)

In [7]:
out

tensor([[[[ 0.0000,  0.2000,  1.2000,  2.2000,  3.2000,  4.2000,  5.2000],
          [ 1.4000,  7.2000,  8.2000,  9.2000, 10.2000, 11.2000, 12.2000],
          [ 2.8000, 14.2000, 15.2000, 16.2000, 17.2000, 18.2000, 19.2000],
          [ 4.2000, 21.2000, 22.2000, 23.2000, 24.2000, 25.2000, 26.2000],
          [ 5.6000, 28.2000, 29.2000, 30.2000, 31.2000, 32.2000, 33.2000]]]],
       device='cuda:0')

In [67]:
n = 3
k = 2

In [68]:
index = torch.arange(n,dtype=torch.int32,device="cuda") * k / n 

In [69]:
weight = 1 - (torch.arange(n,dtype=torch.float32,device="cuda") * k / n - index)

In [70]:
IS.interp_affine(test,out,index,weight,k,n)

tensor([[[[ 0.0000,  0.6667,  1.3333,  2.0000,  2.6667,  3.3333,  4.0000],
          [ 7.0000,  7.6667,  8.3333,  9.0000,  9.6667, 10.3333, 11.0000],
          [14.0000, 14.6667, 15.3333, 16.0000, 16.6667, 17.3333, 18.0000],
          [21.0000, 21.6667, 22.3333, 23.0000, 23.6667, 24.3333, 25.0000],
          [28.0000, 28.6667, 29.3333, 30.0000, 30.6667, 31.3333, 32.0000]]]],
       device='cuda:0')

In [71]:
test

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10., 11., 12., 13.],
          [14., 15., 16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25., 26., 27.],
          [28., 29., 30., 31., 32., 33., 34.]]]], device='cuda:0')