In [1]:
import torch

In [2]:
import interp_function as IF

In [3]:
test = torch.arange(5*7,dtype=torch.float32).reshape(1,1,5,7).to("cuda")

In [4]:
test

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10., 11., 12., 13.],
          [14., 15., 16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25., 26., 27.],
          [28., 29., 30., 31., 32., 33., 34.]]]], device='cuda:0')

In [5]:
IF.ShiftFunctional(test,-0.8)

tensor([[[[ 0.8000,  1.8000,  2.8000,  3.8000,  4.8000,  5.8000,  1.2000],
          [ 7.8000,  8.8000,  9.8000, 10.8000, 11.8000, 12.8000,  2.6000],
          [14.8000, 15.8000, 16.8000, 17.8000, 18.8000, 19.8000,  4.0000],
          [21.8000, 22.8000, 23.8000, 24.8000, 25.8000, 26.8000,  5.4000],
          [28.8000, 29.8000, 30.8000, 31.8000, 32.8000, 33.8000,  6.8000]]]],
       device='cuda:0')

In [6]:
zoom = IF.Zoom()

In [7]:
n = 3
k = 1
zoom(test,k,n)

tensor([[[[ 0.0000,  0.3333,  0.6667,  1.0000,  1.3333,  1.6667,  2.0000],
          [ 7.0000,  7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000],
          [14.0000, 14.3333, 14.6667, 15.0000, 15.3333, 15.6667, 16.0000],
          [21.0000, 21.3333, 21.6667, 22.0000, 22.3333, 22.6667, 23.0000],
          [28.0000, 28.3333, 28.6667, 29.0000, 29.3333, 29.6667, 30.0000]]]],
       device='cuda:0')

In [8]:
import Lowering

In [19]:
inc = 2
HL = Lowering.HarmonicLowering(n,n,inc)

In [20]:
test2 = torch.arange(2*5*7,dtype=torch.float32).reshape(1,2,5,7).to("cuda")

In [21]:
res = HL(test2)
res

tensor([[[[ 0.0000,  0.3333,  0.6667,  1.0000,  1.3333,  1.6667,  2.0000],
          [ 7.0000,  7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000],
          [14.0000, 14.3333, 14.6667, 15.0000, 15.3333, 15.6667, 16.0000],
          [21.0000, 21.3333, 21.6667, 22.0000, 22.3333, 22.6667, 23.0000],
          [28.0000, 28.3333, 28.6667, 29.0000, 29.3333, 29.6667, 30.0000]],

         [[35.0000, 35.3333, 35.6667, 36.0000, 36.3333, 36.6667, 37.0000],
          [42.0000, 42.3333, 42.6667, 43.0000, 43.3333, 43.6667, 44.0000],
          [49.0000, 49.3333, 49.6667, 50.0000, 50.3333, 50.6667, 51.0000],
          [56.0000, 56.3333, 56.6667, 57.0000, 57.3333, 57.6667, 58.0000],
          [63.0000, 63.3333, 63.6667, 64.0000, 64.3333, 64.6667, 65.0000]],

         [[ 0.0000,  0.6667,  1.3333,  2.0000,  2.6667,  3.3333,  4.0000],
          [ 7.0000,  7.6667,  8.3333,  9.0000,  9.6667, 10.3333, 11.0000],
          [14.0000, 14.6667, 15.3333, 16.0000, 16.6667, 17.3333, 18.0000],
          [21.0000, 2

In [13]:
test

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10., 11., 12., 13.],
          [14., 15., 16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25., 26., 27.],
          [28., 29., 30., 31., 32., 33., 34.]]]], device='cuda:0')

In [12]:
res.shape

torch.Size([1, 3, 5, 7])

In [22]:
import harmonic_conv as HC

In [44]:
hc = HC.SingleHarmonicConv2d(in_channels=2,out_channels=3,kernel_size=(3,3),bias=False,anchor=3).to("cuda")

In [45]:
hc.lowered_weight = torch.nn.Parameter(torch.ones_like(hc.lowered_weight))

In [46]:
test3 = torch.zeros(1,2,5,7,dtype=torch.float32,device="cuda")

In [47]:
test3[0,0,3,1] = 1
test3[0,1,4,3] = 1

In [48]:
hc(test3)

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 2.0000, 1.3333, 1.0000, 0.6667, 0.3333, 0.0000],
          [0.0000, 2.0000, 1.3333, 2.0000, 1.3333, 1.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 2.0000, 1.3333, 1.0000, 0.6667, 0.3333, 0.0000],
          [0.0000, 2.0000, 1.3333, 2.0000, 1.3333, 1.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 2.0000, 1.3333, 1.0000, 0.6667, 0.3333, 0.0000],
          [0.0000, 2.0000, 1.3333, 2.0000, 1.3333, 1.0000, 0.0000]]]],
       device='cuda:0', grad_fn=<CudnnConvolutionBackward>)

In [49]:
hc.HL(test3)

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.3333, 0.6667, 1.0000, 0.6667, 0.3333, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.6667, 0.6667, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0